### PR TITLE
initial commit and start of North chla function

### PR DESCRIPTION
**Pull request by lawinslow**

### CODE REVIEW

**Comment by lawinslow** [comment]
@cgries, thoughts? You ok with us hitting LTER data directly?

**Comment by cgries** [comment]
from the database or via DataONE?

**Comment by cgries** [comment]
oh, I see, you are hitting the website. I don't have any problems with that. But DataONE may be the better way. You won't get the most recent data there, though.

**Comment by lawinslow** [comment]
Are all the same data sets up on data one? And how often are the data sets updated on data one?

**Comment by cgries** [comment]
they should all be on DataONE and are updated annually.

**Comment by lawinslow** [comment]
@cgries @mbjones
Was there ever a new dataone R package on CRAN?

**Comment by mbjones** [comment]
@lawinslow `dataone` v2 is not on CRAN yet, but @sbpcs59 and I are close -- it can be installed from Github if you get the other dependency packages installed first.  These dependencies need to be on CRAN first before we can release the dataone v2 package. In the meantime, I've provided install instructions in the [README file](https://github.com/DataONEorg/rdataone/blob/master/README.rst#user-content-version-2-alpha) to show how to install v2 and its dependencies.  Note there is an outstanding issue on Mac OS due to [Apple breaking their version of curl](https://github.com/DataONEorg/rdataone/issues/24) in recent releases.  Still working on a work-around for that too.

Please let us know if you have any issues.

**Comment by lawinslow** [comment]
@mbjones, cool. Thanks. I'll probably move forward with directly hitting the NTL-LTER database until the DataOne Stuff is finalized. If I follow the rdataone repo, will you make relevant CRAN announcements there?

**Comment by mbjones** [comment]
@lawinslow Yes, we'll make announcements there.

**Comment by lawinslow** [comment]
Great, looking forward do it!

**Pull request merged**
